# Generated by Django 5.1.6 on 2025-03-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='phone2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
